name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  # Write permission is required to upload the dependency graph.
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Compile exercises
      run: sbt compile
    - name: Compile lectures
      run: sbt fastCompile
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
